"use client";

import React from "react";
import { Select, SelectItem } from "@heroui/react";

interface CountrySelectorProps {
  value?: string;
  onChange?: (value: string) => void;
  placeholder?: string;
  label?: string;
  className?: string;
}

const countries = [
  { code: "+251", name: "Ethiopia", flag: "🇪🇹" },
  { code: "+1", name: "United States", flag: "🇺🇸" },
  { code: "+44", name: "United Kingdom", flag: "🇬🇧" },
  { code: "+49", name: "Germany", flag: "🇩🇪" },
  { code: "+33", name: "France", flag: "🇫🇷" },
  { code: "+39", name: "Italy", flag: "🇮🇹" },
  { code: "+34", name: "Spain", flag: "🇪🇸" },
  { code: "+31", name: "Netherlands", flag: "🇳🇱" },
  { code: "+46", name: "Sweden", flag: "🇸🇪" },
  { code: "+47", name: "Norway", flag: "🇳🇴" },
  { code: "+45", name: "Denmark", flag: "🇩🇰" },
  { code: "+41", name: "Switzerland", flag: "🇨🇭" },
  { code: "+43", name: "Austria", flag: "🇦🇹" },
  { code: "+32", name: "Belgium", flag: "🇧🇪" },
  { code: "+351", name: "Portugal", flag: "🇵🇹" },
  { code: "+30", name: "Greece", flag: "🇬🇷" },
  { code: "+48", name: "Poland", flag: "🇵🇱" },
  { code: "+420", name: "Czech Republic", flag: "🇨🇿" },
  { code: "+36", name: "Hungary", flag: "🇭🇺" },
  { code: "+40", name: "Romania", flag: "🇷🇴" },
  { code: "+359", name: "Bulgaria", flag: "🇧🇬" },
  { code: "+385", name: "Croatia", flag: "🇭🇷" },
  { code: "+386", name: "Slovenia", flag: "🇸🇮" },
  { code: "+421", name: "Slovakia", flag: "🇸🇰" },
  { code: "+370", name: "Lithuania", flag: "🇱🇹" },
  { code: "+371", name: "Latvia", flag: "🇱🇻" },
  { code: "+372", name: "Estonia", flag: "🇪🇪" },
  { code: "+358", name: "Finland", flag: "🇫🇮" },
  { code: "+353", name: "Ireland", flag: "🇮🇪" },
  { code: "+352", name: "Luxembourg", flag: "🇱🇺" },
  { code: "+356", name: "Malta", flag: "🇲🇹" },
  { code: "+357", name: "Cyprus", flag: "🇨🇾" },
  { code: "+20", name: "Egypt", flag: "🇪🇬" },
  { code: "+27", name: "South Africa", flag: "🇿🇦" },
  { code: "+234", name: "Nigeria", flag: "🇳🇬" },
  { code: "+254", name: "Kenya", flag: "🇰🇪" },
  { code: "+256", name: "Uganda", flag: "🇺🇬" },
  { code: "+255", name: "Tanzania", flag: "🇹🇿" },
  { code: "+250", name: "Rwanda", flag: "🇷🇼" },
  { code: "+257", name: "Burundi", flag: "🇧🇮" },
  { code: "+252", name: "Somalia", flag: "🇸🇴" },
  { code: "+253", name: "Djibouti", flag: "🇩🇯" },
  { code: "+249", name: "Sudan", flag: "🇸🇩" },
  { code: "+211", name: "South Sudan", flag: "🇸🇸" },
  { code: "+235", name: "Chad", flag: "🇹🇩" },
  { code: "+236", name: "Central African Republic", flag: "🇨🇫" },
  { code: "+237", name: "Cameroon", flag: "🇨🇲" },
  { code: "+238", name: "Cape Verde", flag: "🇨🇻" },
  { code: "+239", name: "São Tomé and Príncipe", flag: "🇸🇹" },
  { code: "+240", name: "Equatorial Guinea", flag: "🇬🇶" },
  { code: "+241", name: "Gabon", flag: "🇬🇦" },
  { code: "+242", name: "Republic of the Congo", flag: "🇨🇬" },
  { code: "+243", name: "Democratic Republic of the Congo", flag: "🇨🇩" },
  { code: "+244", name: "Angola", flag: "🇦🇴" },
  { code: "+245", name: "Guinea-Bissau", flag: "🇬🇼" },
  { code: "+246", name: "British Indian Ocean Territory", flag: "🇮🇴" },
  { code: "+247", name: "Ascension Island", flag: "🇦🇨" },
  { code: "+248", name: "Seychelles", flag: "🇸🇨" },
  { code: "+260", name: "Zambia", flag: "🇿🇲" },
  { code: "+261", name: "Madagascar", flag: "🇲🇬" },
  { code: "+262", name: "Réunion", flag: "🇷🇪" },
  { code: "+263", name: "Zimbabwe", flag: "🇿🇼" },
  { code: "+264", name: "Namibia", flag: "🇳🇦" },
  { code: "+265", name: "Malawi", flag: "🇲🇼" },
  { code: "+266", name: "Lesotho", flag: "🇱🇸" },
  { code: "+267", name: "Botswana", flag: "🇧🇼" },
  { code: "+268", name: "Eswatini", flag: "🇸🇿" },
  { code: "+269", name: "Comoros", flag: "🇰🇲" },
  { code: "+290", name: "Saint Helena", flag: "🇸🇭" },
  { code: "+291", name: "Eritrea", flag: "🇪🇷" },
  { code: "+297", name: "Aruba", flag: "🇦🇼" },
  { code: "+298", name: "Faroe Islands", flag: "🇫🇴" },
  { code: "+299", name: "Greenland", flag: "🇬🇱" },
  { code: "+350", name: "Gibraltar", flag: "🇬🇮" },
  { code: "+354", name: "Iceland", flag: "🇮🇸" },
  { code: "+355", name: "Albania", flag: "🇦🇱" },
  { code: "+376", name: "Andorra", flag: "🇦🇩" },
  { code: "+377", name: "Monaco", flag: "🇲🇨" },
  { code: "+378", name: "San Marino", flag: "🇸🇲" },
  { code: "+380", name: "Ukraine", flag: "🇺🇦" },
  { code: "+381", name: "Serbia", flag: "🇷🇸" },
  { code: "+382", name: "Montenegro", flag: "🇲🇪" },
  { code: "+383", name: "Kosovo", flag: "🇽🇰" },
  { code: "+385", name: "Croatia", flag: "🇭🇷" },
  { code: "+386", name: "Slovenia", flag: "🇸🇮" },
  { code: "+387", name: "Bosnia and Herzegovina", flag: "🇧🇦" },
  { code: "+389", name: "North Macedonia", flag: "🇲🇰" },
  { code: "+390", name: "Vatican City", flag: "🇻🇦" },
  { code: "+7", name: "Russia", flag: "🇷🇺" },
  { code: "+7", name: "Kazakhstan", flag: "🇰🇿" },
  { code: "+90", name: "Turkey", flag: "🇹🇷" },
  { code: "+91", name: "India", flag: "🇮🇳" },
  { code: "+92", name: "Pakistan", flag: "🇵🇰" },
  { code: "+93", name: "Afghanistan", flag: "🇦🇫" },
  { code: "+94", name: "Sri Lanka", flag: "🇱🇰" },
  { code: "+95", name: "Myanmar", flag: "🇲🇲" },
  { code: "+960", name: "Maldives", flag: "🇲🇻" },
  { code: "+961", name: "Lebanon", flag: "🇱🇧" },
  { code: "+962", name: "Jordan", flag: "🇯🇴" },
  { code: "+963", name: "Syria", flag: "🇸🇾" },
  { code: "+964", name: "Iraq", flag: "🇮🇶" },
  { code: "+965", name: "Kuwait", flag: "🇰🇼" },
  { code: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "+967", name: "Yemen", flag: "🇾🇪" },
  { code: "+968", name: "Oman", flag: "🇴🇲" },
  { code: "+970", name: "Palestine", flag: "🇵🇸" },
  { code: "+971", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "+972", name: "Israel", flag: "🇮🇱" },
  { code: "+973", name: "Bahrain", flag: "🇧🇭" },
  { code: "+974", name: "Qatar", flag: "🇶🇦" },
  { code: "+975", name: "Bhutan", flag: "🇧🇹" },
  { code: "+976", name: "Mongolia", flag: "🇲🇳" },
  { code: "+977", name: "Nepal", flag: "🇳🇵" },
  { code: "+992", name: "Tajikistan", flag: "🇹🇯" },
  { code: "+993", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "+994", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "+995", name: "Georgia", flag: "🇬🇪" },
  { code: "+996", name: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "+998", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "+81", name: "Japan", flag: "🇯🇵" },
  { code: "+82", name: "South Korea", flag: "🇰🇷" },
  { code: "+84", name: "Vietnam", flag: "🇻🇳" },
  { code: "+86", name: "China", flag: "🇨🇳" },
  { code: "+852", name: "Hong Kong", flag: "🇭🇰" },
  { code: "+853", name: "Macau", flag: "🇲🇴" },
  { code: "+855", name: "Cambodia", flag: "🇰🇭" },
  { code: "+856", name: "Laos", flag: "🇱🇦" },
  { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+886", name: "Taiwan", flag: "🇹🇼" },
  { code: "+60", name: "Malaysia", flag: "🇲🇾" },
  { code: "+61", name: "Australia", flag: "🇦🇺" },
  { code: "+62", name: "Indonesia", flag: "🇮🇩" },
  { code: "+63", name: "Philippines", flag: "🇵🇭" },
  { code: "+64", name: "New Zealand", flag: "🇳🇿" },
  { code: "+65", name: "Singapore", flag: "🇸🇬" },
  { code: "+66", name: "Thailand", flag: "🇹🇭" },
  { code: "+673", name: "Brunei", flag: "🇧🇳" },
  { code: "+674", name: "Nauru", flag: "🇳🇷" },
  { code: "+675", name: "Papua New Guinea", flag: "🇵🇬" },
  { code: "+676", name: "Tonga", flag: "🇹🇴" },
  { code: "+677", name: "Solomon Islands", flag: "🇸🇧" },
  { code: "+678", name: "Vanuatu", flag: "🇻🇺" },
  { code: "+679", name: "Fiji", flag: "🇫🇯" },
  { code: "+680", name: "Palau", flag: "🇵🇼" },
  { code: "+681", name: "Wallis and Futuna", flag: "🇼🇫" },
  { code: "+682", name: "Cook Islands", flag: "🇨🇰" },
  { code: "+683", name: "Niue", flag: "🇳🇺" },
  { code: "+684", name: "American Samoa", flag: "🇦🇸" },
  { code: "+685", name: "Samoa", flag: "🇼🇸" },
  { code: "+686", name: "Kiribati", flag: "🇰🇮" },
  { code: "+687", name: "New Caledonia", flag: "🇳🇨" },
  { code: "+688", name: "Tuvalu", flag: "🇹🇻" },
  { code: "+689", name: "French Polynesia", flag: "🇵🇫" },
  { code: "+690", name: "Tokelau", flag: "🇹🇰" },
  { code: "+691", name: "Micronesia", flag: "🇫🇲" },
  { code: "+692", name: "Marshall Islands", flag: "🇲🇭" },
  { code: "+850", name: "North Korea", flag: "🇰🇵" },
  { code: "+880", name: "Bangladesh", flag: "🇧🇩" },
  { code: "+886", name: "Taiwan", flag: "🇹🇼" },
  { code: "+960", name: "Maldives", flag: "🇲🇻" },
  { code: "+961", name: "Lebanon", flag: "🇱🇧" },
  { code: "+962", name: "Jordan", flag: "🇯🇴" },
  { code: "+963", name: "Syria", flag: "🇸🇾" },
  { code: "+964", name: "Iraq", flag: "🇮🇶" },
  { code: "+965", name: "Kuwait", flag: "🇰🇼" },
  { code: "+966", name: "Saudi Arabia", flag: "🇸🇦" },
  { code: "+967", name: "Yemen", flag: "🇾🇪" },
  { code: "+968", name: "Oman", flag: "🇴🇲" },
  { code: "+970", name: "Palestine", flag: "🇵🇸" },
  { code: "+971", name: "United Arab Emirates", flag: "🇦🇪" },
  { code: "+972", name: "Israel", flag: "🇮🇱" },
  { code: "+973", name: "Bahrain", flag: "🇧🇭" },
  { code: "+974", name: "Qatar", flag: "🇶🇦" },
  { code: "+975", name: "Bhutan", flag: "🇧🇹" },
  { code: "+976", name: "Mongolia", flag: "🇲🇳" },
  { code: "+977", name: "Nepal", flag: "🇳🇵" },
  { code: "+992", name: "Tajikistan", flag: "🇹🇯" },
  { code: "+993", name: "Turkmenistan", flag: "🇹🇲" },
  { code: "+994", name: "Azerbaijan", flag: "🇦🇿" },
  { code: "+995", name: "Georgia", flag: "🇬🇪" },
  { code: "+996", name: "Kyrgyzstan", flag: "🇰🇬" },
  { code: "+998", name: "Uzbekistan", flag: "🇺🇿" },
  { code: "+55", name: "Brazil", flag: "🇧🇷" },
  { code: "+54", name: "Argentina", flag: "🇦🇷" },
  { code: "+56", name: "Chile", flag: "🇨🇱" },
  { code: "+57", name: "Colombia", flag: "🇨🇴" },
  { code: "+58", name: "Venezuela", flag: "🇻🇪" },
  { code: "+51", name: "Peru", flag: "🇵🇪" },
  { code: "+52", name: "Mexico", flag: "🇲🇽" },
  { code: "+53", name: "Cuba", flag: "🇨🇺" },
  { code: "+1", name: "Canada", flag: "🇨🇦" },
  { code: "+506", name: "Costa Rica", flag: "🇨🇷" },
  { code: "+507", name: "Panama", flag: "🇵🇦" },
  { code: "+502", name: "Guatemala", flag: "🇬🇹" },
  { code: "+503", name: "El Salvador", flag: "🇸🇻" },
  { code: "+504", name: "Honduras", flag: "🇭🇳" },
  { code: "+505", name: "Nicaragua", flag: "🇳🇮" },
  { code: "+501", name: "Belize", flag: "🇧🇿" },
  { code: "+509", name: "Haiti", flag: "🇭🇹" },
  { code: "+1", name: "Jamaica", flag: "🇯🇲" },
  { code: "+1", name: "Dominican Republic", flag: "🇩🇴" },
  { code: "+1", name: "Trinidad and Tobago", flag: "🇹🇹" },
  { code: "+1", name: "Barbados", flag: "🇧🇧" },
  { code: "+1", name: "Bahamas", flag: "🇧🇸" },
  { code: "+1", name: "Grenada", flag: "🇬🇩" },
  { code: "+1", name: "Saint Lucia", flag: "🇱🇨" },
  { code: "+1", name: "Saint Vincent and the Grenadines", flag: "🇻🇨" },
  { code: "+1", name: "Antigua and Barbuda", flag: "🇦🇬" },
  { code: "+1", name: "Dominica", flag: "🇩🇲" },
  { code: "+1", name: "Saint Kitts and Nevis", flag: "🇰🇳" },
  { code: "+590", name: "Guadeloupe", flag: "🇬🇵" },
  { code: "+596", name: "Martinique", flag: "🇲🇶" },
  { code: "+594", name: "French Guiana", flag: "🇬🇫" },
  { code: "+508", name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  { code: "+590", name: "Saint Barthélemy", flag: "🇧🇱" },
  { code: "+590", name: "Saint Martin", flag: "🇲🇫" },
  { code: "+596", name: "Martinique", flag: "🇲🇶" },
  { code: "+594", name: "French Guiana", flag: "🇬🇫" },
  { code: "+508", name: "Saint Pierre and Miquelon", flag: "🇵🇲" },
  { code: "+590", name: "Saint Barthélemy", flag: "🇧🇱" },
  { code: "+590", name: "Saint Martin", flag: "🇲🇫" },
];

export default function CountrySelector({
  value,
  onChange,
  placeholder = "Select Country",
  label = "Country",
  className = "",
}: CountrySelectorProps) {
  return (
    <Select
      value={value}
      onSelectionChange={(keys) => {
        const selectedKey = Array.from(keys)[0] as string;
        onChange?.(selectedKey);
      }}
      placeholder={placeholder}
      label={label}
      className={className}
      color="primary"
      variant="bordered"
      size="md"
      classNames={{
        trigger: "min-h-12",
        value: "text-left",
      }}
    >
      {countries.map((country) => (
        <SelectItem
          key={country.code}
          textValue={`${country.flag} ${country.name} (${country.code})`}
        >
          <div className="flex items-center gap-2">
            <span className="text-lg">{country.flag}</span>
            <span className="font-medium">{country.name}</span>
            <span className="text-sm text-gray-500">({country.code})</span>
          </div>
        </SelectItem>
      ))}
    </Select>
  );
}
